# This configuration file supports adding reference ranges to PFE
# Observations (which are later used in graphing observation trends)
# and displaying cut lines in observation trend graphs

# PROMIS-10 Global Physical Health (GPH) score
"71972-4":
  range:
    low: 4
    high: 20
  cut_points: []

# PROMIS-10 Global Mental Health (GMH) score
"71970-8":
  range:
    low: 4
    high: 20
  cut_points: []

# PROMIS-10 Global Physical Health (GPH) score T-score
"71971-6":
  range:
    low: 16.2
    high: 67.7
  cut_points:
    - limit: 36
      label: "Poor"
      color: "rgba(255, 192, 192, 0.4)"
    - limit: 43
      label: "Fair"
      color: "rgba(255, 255, 192, 0.4)"
    - limit: 51
      label: "Good"
      color: "rgba(192, 255, 192, 0.4)"
    - limit: 58
      label: "Very Good"
      color: "rgba(192, 255, 192, 0.4)"
    - limit:
      label: "Excellent"
      color: "rgba(192, 255, 192, 0.4)"

# PROMIS-10 Global Mental Health (GMH) score T-score
"71969-0":
  range:
    low: 21.2
    high: 67.6
  cut_points:
    - limit: 34
      label: "Poor"
      color: "rgba(255, 192, 192, 0.4)"
    - limit: 42
      label: "Fair"
      color: "rgba(255, 255, 192, 0.4)"
    - limit: 49
      label: "Good"
      color: "rgba(192, 255, 192, 0.4)"
    - limit: 57
      label: "Very Good"
      color: "rgba(192, 255, 192, 0.4)"
    - limit:
      label: "Excellent"
      color: "rgba(192, 255, 192, 0.4)"


# Generalized anxiety disorder 7 item (GAD-7) total score
"70274-6":
  range:
    low: 0
    high: 21
  cut_points:
    - limit: 4
      label: "Minimal anxiety"
      color: "rgba(192, 255, 192, 0.4)"
    - limit: 9
      label: "Mild anxiety"
      color: "rgba(255, 255, 192, 0.4)"
    - limit: 14
      label: "Moderate anxiety"
      color: "rgba(255, 255, 192, 0.4)"
    - limit:
      label: "Moderate to severe anxiety"
      color: "rgba(255, 192, 192, 0.4)"


# PROMIS short form - pain interference 6a - version 1.0 raw score
"90974-7":
  range:
    low: 6
    high: 30

# PROMIS pain interference - version 1.0 Tscore
"77865-4":
  range:
    low: 41.6
    high: 90.5


# PROMIS short form - physical function 6b - version 1.2 raw score
"77797-9":
  range:
    low: 6
    high: 30

# PROMIS physical function - version 1.0 Tscore
"77866-2":
  range:
    low: 16.2
    high: 99.7


#  Pain severity - 0-10 verbal numeric rating [Score] - Reported
"72514-3":
  range:
    low: 0
    high: 10


# Patient Health Questionnaire 9 item (PHQ-9) total score
"44261-6":
  range:
    low: 0
    high: 27
  cut_points:
    - limit: 5
      label: "Minimal"
      color: "rgba(192, 255, 192, 0.4)"
    - limit: 10
      label: "Mild"
      color: "rgba(192, 255, 192, 0.4)"
    - limit: 15
      label: "Moderate"
      color: "rgba(255, 255, 192, 0.4)"
    - limit: 20
      label: "Moderately Severe"
      color: "rgba(255, 192, 192, 0.4)"
    - limit:
      label: "Severe"
      color: "rgba(255, 192, 192, 0.4)"
