name: Sample Data Scraper

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-and-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Check for changes in sample-data-fsh repository
        id: check-changes
        run: |
          # Clone the sample-data-fsh repository
          git clone https://github.com/paciowg/sample-data-fsh.git /tmp/sample-data-fsh
          cd /tmp/sample-data-fsh

          # Get the latest commit hash
          LATEST_COMMIT=$(git rev-parse HEAD)

          # Create a file to store the last checked commit if it doesn't exist
          COMMIT_FILE=".last_sample_data_commit"
          if [ ! -f "$COMMIT_FILE" ]; then
            echo "First run, creating commit file"
            echo "$LATEST_COMMIT" > "$COMMIT_FILE"
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          else
            # Read the last checked commit
            LAST_CHECKED_COMMIT=$(cat "$COMMIT_FILE")

            # Compare commits
            if [ "$LATEST_COMMIT" != "$LAST_CHECKED_COMMIT" ]; then
              echo "Changes detected in sample-data-fsh repository"
              echo "$LATEST_COMMIT" > "$COMMIT_FILE"
              echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
            else
              echo "No changes detected in sample-data-fsh repository"
              echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
            fi
          fi

          # Move the commit file back to the repository
          mv "$COMMIT_FILE" $GITHUB_WORKSPACE/

      - name: Commit and push updated last commit file
        if: env.CHANGES_DETECTED == 'true'
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add .last_sample_data_commit
          git commit -m "Update last checked commit for sample-data-fsh" || echo "No changes to commit"
          git push

      - name: Run sample data scraper
        if: env.CHANGES_DETECTED == 'true'
        run: |
          bundle exec rake sample_data:scrape

      - name: Commit and push scraped data
        if: env.CHANGES_DETECTED == 'true'
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add sample_use_cases
          git commit -m "Update sample FHIR resources from sample-data-fsh" || echo "No changes to commit"
          git push
